Repository googleapis/nodejs-media-translation, pull requests merged in 2020-05, with the labels that each got.

#39 fix: regen protos and tests, formatting
  synth.metadata
  test/gapic_speech_translation_service_v1beta1.ts
Labels: automerge, cla: yes

#40 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#41 fix: streaming mic sample
  .repo-metadata.json
  README.md
  linkinator.config.json
  samples/translate_from_mic.js
Labels: cla: yes
