Repository googleapis/nodejs-media-translation, pull requests merged in 2020-06, with the labels that each got.

#42 docs: update product doc links
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none

#43 chore: add proto3Optional field
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: none

#46 feat: move ts target to es2018 from es2016
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  protos/protos.js
  src/v1beta1/speech_translation_service_client.ts
  synth.metadata
  tsconfig.json
Labels: automerge, cla: yes, context: partial

#50 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#51 fix: proper fallback option handling
  src/v1beta1/speech_translation_service_client.ts
  synth.metadata
Labels: cla: yes, context: none

#48 feat(samples): demonstrate real-time conversation translation
  samples/translate_from_mic.js
Labels: automerge, cla: yes

#52 chore: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#53 build: add config .gitattributes
  .gitattributes
  .kokoro/.gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
