Repository googleapis/nodejs-media-translation, pull requests merged in 2020-11, with the labels that each got.

#93 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: mediatranslation, automerge, cla: yes, context: full

#94 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1beta1/speech_translation_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: mediatranslation, automerge, cla: yes

#97 fix(browser): check for fetch on window
  src/v1beta1/speech_translation_service_client.ts
  synth.metadata
Labels: api: mediatranslation, cla: yes, context: none

#99 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: mediatranslation, automerge, cla: yes, context: full
