Repository googleapis/nodejs-media-translation, pull requests merged in 2020-07, with the labels that each got.

#54 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#55 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#57 chore: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#59 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#63 build: fix typo in publish
  .kokoro/publish.sh
  synth.metadata
Labels: automerge, cla: yes, context: partial

#64 chore: add config files for cloud-rad for node.js
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#65 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#66 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#67 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#68 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#69 build: protos update
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none
