Repository googleapis/nodejs-media-translation, pull requests merged in 2021-06, with the labels that each got.

#152 chore(nodejs): remove api-extractor dependencies
  package.json
Labels: api: mediatranslation, automerge, cla: yes

#154 samples: fixes a typo
  samples/translate_from_file.js
Labels: api: mediatranslation, cla: yes, samples

#155 samples: another typo in comments
  README.md
  samples/quickstart.js
Labels: api: mediatranslation, cla: yes

#161 fix(deps): google-gax v2.17.0 with mTLS
  package.json
Labels: api: mediatranslation, automerge, cla: yes, owlbot:run
